# Generated by Django 5.2.8 on 2025-11-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_priority_alter_todo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
